### ISSUE TITLE
Img

### ISSUE THREAD

**Issue by trentgoing** [Team-Pulsar/project-greenfield#39]
https://github.com/Team-Pulsar/project-greenfield/blob/834c22b3f8a3cc55291aedb01f900c3a1ab447be/src/components/questions/Search.js#L35

Is this redundant with the image saved locally?

**Comment by whiskywolf88** [comment]
I originally added the local image but realized webpack would require an additional dependency/config for render. I have since replaced this with a React-Bootstrap icon!
